# Generated by Django 4.1 on 2022-10-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, null=True, verbose_name='Nome')),
                ('nascimento', models.DateField(max_length=9, null=True, verbose_name='Nascimento')),
                ('estadocivil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=15, null=True, verbose_name='Estadocivil')),
                ('rg', models.CharField(max_length=15, null=True, verbose_name='Rg')),
                ('cpf', models.CharField(max_length=15, null=True, verbose_name='CPF')),
                ('pis', models.CharField(max_length=16, null=True, verbose_name='PIS')),
                ('cns', models.CharField(max_length=16, null=True, verbose_name='Cns')),
                ('ctps', models.CharField(max_length=7, null=True, verbose_name='Ctps número:')),
                ('ctpsserie', models.CharField(max_length=4, null=True, verbose_name='Série')),
                ('ctpsuf', models.CharField(max_length=2, null=True, verbose_name='UF')),
                ('genero', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO'), ('NÃO DEFINIDO', 'NÃO DEFINIDO')], max_length=16, null=True, verbose_name='Genero')),
                ('phone', models.CharField(max_length=16, null=True, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Colaborador_fotos', verbose_name='Foto')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=10, null=True, verbose_name='Status')),
            ],
        ),
        migrations.DeleteModel(
            name='AppwModel',
        ),
    ]
