# Generated by Django 4.1 on 2022-10-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaborador_delete_appwmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cns',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='Cns'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='pis',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='PIS'),
        ),
    ]
