# Generated by Django 4.1 on 2022-10-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_alter_colaborador_cns_alter_colaborador_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(max_length=20, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado',
            field=models.CharField(max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
