# Generated by Django 4.1 on 2022-10-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_colaborador_cidade_colaborador_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='estado',
        ),
    ]
