# Generated by Django 4.1 on 2022-10-14 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colaboradores', '0005_remove_colaborador_cidade_remove_colaborador_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='criadopor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
