# Generated by Django 4.1 on 2022-10-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0006_colaborador_criadopor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Colaborador_foto', verbose_name='Foto'),
        ),
    ]
