# Generated by Django 4.1 on 2022-10-11 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, null=True, verbose_name='Nome do setor')),
                ('sigla', models.CharField(max_length=7, null=True, verbose_name='Sigla do Setor')),
                ('descricao', models.CharField(blank=True, max_length=70, null=True, verbose_name='Descrição do Setor')),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(max_length=25, null=True, verbose_name='Cidade')),
                ('municipio', models.CharField(max_length=25, null=True, verbose_name='Municipio')),
                ('telefone', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Telefone')),
            ],
        ),
    ]
