# Generated by Django 4.1 on 2022-10-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, null=True, verbose_name='Nome')),
                ('nascimento', models.DateField(max_length=9, null=True, verbose_name='Nascimento')),
                ('idade', models.IntegerField()),
                ('estadocivil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=15, null=True, verbose_name='Estadocivil')),
                ('escolaridade', models.CharField(choices=[('N', 'Nenhum'), ('F', 'Ensino Fundamental'), ('M', 'Ensino Médio'), ('S', 'Ensino Superior')], max_length=15, null=True, verbose_name='Escolaridade')),
                ('telefone', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email')),
            ],
        ),
    ]
