# Generated by Django 4.1 on 2022-10-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoamodel_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoamodel',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO'), ('NÃO DEFINIDO', 'NÃO DEFINIDO')], max_length=16, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='pessoamodel',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pessoamodel',
            name='nascimento',
            field=models.DateTimeField(max_length=9, null=True, verbose_name='Nascimento'),
        ),
    ]
