# Generated by Django 4.1 on 2022-10-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoamodel_genero_pessoamodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoamodel',
            name='cidade',
            field=models.CharField(max_length=20, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pessoamodel',
            name='estado',
            field=models.CharField(max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
