# Generated by Django 4.1 on 2022-10-15 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoas', '0005_alter_pessoamodel_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoamodel',
            name='criadopor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
