# Generated by Django 4.1 on 2022-10-11 17:20

from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('tipo', models.CharField(choices=[('Documento', 'Documento'), ('Atestado', 'Atestado'), ('Foto', 'Foto'), ('PDF', 'PDF')], max_length=10)),
                ('anexo', models.ImageField(null=True, upload_to=documentos.models.userdoc, verbose_name='Anexo')),
                ('obs', models.TextField(null=True, verbose_name='Observação')),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='colaboradores.colaborador', verbose_name='Colaborador')),
            ],
        ),
    ]
