# Generated by Django 4.1 on 2022-10-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, null=True, verbose_name='Nome da Unidade')),
                ('ramal', models.IntegerField(blank=True, null=True, verbose_name='Ramal')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=10, null=True, verbose_name='Status')),
                ('descricao', models.CharField(blank=True, max_length=70, null=True, verbose_name='Descricao')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setor.setor', verbose_name='Setor')),
            ],
        ),
    ]
