# Generated by Django 4.1 on 2022-10-16 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55, null=True, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='Cpf')),
                ('telefone', models.CharField(max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email')),
                ('cep', models.CharField(max_length=20, null=True, verbose_name='Cep')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
