# Generated by Django 4.1 on 2022-10-16 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geralista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menssagem', models.TextField(max_length=1000, null=True, verbose_name='Menssagem')),
                ('arquivo1', models.FileField(null=True, upload_to='arquivo1/', verbose_name='arquivo1')),
                ('arquivo2', models.FileField(null=True, upload_to='arquivo2/', verbose_name='arquivo1')),
                ('arquivo3', models.FileField(null=True, upload_to='arquivo3/', verbose_name='arquivo1')),
                ('criadopor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
