# Generated by Django 4.1 on 2022-10-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geralista', '0002_alter_geralista_arquivo1_alter_geralista_arquivo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geralista',
            name='arquivo2',
            field=models.FileField(blank=True, null=True, upload_to='arquivo2/', verbose_name='arquivo2'),
        ),
        migrations.AlterField(
            model_name='geralista',
            name='arquivo3',
            field=models.FileField(blank=True, null=True, upload_to='arquivo3/', verbose_name='arquivo3'),
        ),
    ]
