# Generated by Django 4.1 on 2022-10-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geralista', '0003_alter_geralista_arquivo2_alter_geralista_arquivo3'),
    ]

    operations = [
        migrations.AddField(
            model_name='geralista',
            name='titulo',
            field=models.CharField(max_length=50, null=True, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='geralista',
            name='arquivo1',
            field=models.FileField(default=1, upload_to='arquivo1/', verbose_name='arquivo1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geralista',
            name='arquivo2',
            field=models.FileField(upload_to='arquivo2/', verbose_name='arquivo2'),
        ),
        migrations.AlterField(
            model_name='geralista',
            name='arquivo3',
            field=models.FileField(blank=True, upload_to='arquivo3/', verbose_name='arquivo3'),
        ),
    ]
