# Generated by Django 4.1 on 2022-10-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0001_initial'),
        ('unidades', '0001_initial'),
        ('colaboradores', '0002_colaborador_delete_appwmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=30, null=True, verbose_name='Número Contrato')),
                ('matricula', models.IntegerField(verbose_name='Matrícula')),
                ('datainicio', models.DateField(verbose_name='Data Início')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colaboradores.colaborador', verbose_name='Colaborador')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setor.setor', verbose_name='Setor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidades.unidade', verbose_name='Unidade')),
            ],
        ),
    ]
