# Generated by Django 4.1 on 2022-10-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='contrato',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Número Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setor.setor', unique=True, verbose_name='Setor'),
        ),
    ]
