# Generated by Django 4.1 on 2022-10-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
        ('contratos', '0002_alter_contrato_contrato_alter_contrato_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setor.setor', verbose_name='Setor'),
        ),
    ]
