# Generated by Django 4.1 on 2022-10-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contrato_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='matricula',
            field=models.IntegerField(unique=True, verbose_name='Matrícula'),
        ),
    ]
